### ISSUE TITLE
列举并解释你知道的选择器类型

### ISSUE THREAD

**Issue by 994AK** [994AK/interview#20]
## 通配选择器
> 选中全部或者选择其中的全部
```CSS
 * {  color: red }
 *.app{ color:red}
```

## 类选择器 与 ID 选择器
> 类选择器是通过 class来选择对应的标签 ，ID选择器是通过标签中的ID进行一个选择
```CSS
 #id { color: red;}
 .class { color: red}
``` 
## 元素选择器
> 比如标签叫 span就等于页面的元素，通过标签来选择

## 普通兄弟选择器 
>  A ~ B 在父级相同的AB下，选择A元素同层级的B元素

##  相邻兄弟选择器
>  A + B 在父级相同的情况下，选择A元素同层级的B元素第一个;

## 后代选择器
> A B 在父级的后代都被选中；比如A父级后代的B，满足全部选中

## 属性选择器
> [attr] 代表命名的属性元素

1. [attr = val] ---- 表示attr命名的属性，属性值为val的元素被选中
2. [attr~=val] --- 表示attr命名的属性，属性为vall为空格分隔的列表被选中
3. [attr^=val] --- 表示attr命名的属性，属性值为val为开头的被选中
4. [attr$=val] --- 表示attr命名的属性，属性值为val为结尾的被选中
5. [attr*=val] ---  表示attr命名的属性，属性值至少包含一个val的被选中
