### ISSUE TITLE
如何清除浮动

### ISSUE THREAD

**Issue by 994AK** [994AK/interview#40]
1.浮动元素中使用：clear元素
2.父容器给`::after`伪元素，空字符串进行清处浮动
```CSS
        .clear::after {
            content: " ";
            clear: both;
            display: block;
        }

```
`.clear`是父容器，注意盒模型必须是block占满一行
