### ISSUE TITLE
如何优化网页的打印样式？

### ISSUE THREAD

**Issue by 994AK** [994AK/interview#51]
``` CSS

/* 打印的时候，页面文字是20px */
@media print {
body { font-size: 20px; }
}

```
